### ISSUE TITLE
Add possibility to setup body and header rules globally 

### ISSUE THREAD

**Issue by cepreu2github** [anystub/anystub#47]
Now we have to pervert in this way:
```
    @Rule
    public TestName name = new TestName();

    @Before
    public void setUpStubClient() {
        BaseManagerImpl.instance().getBase(name.getMethodName() + ".yml")
                .addProperty(HTTP_PROPERTY, HTTP_PROPERTY_BODY, "processxml");
    }
```
Or write at every method `StubHttpClient.addBodyRule("processxml");`

None of this options are good. Probably should be some way to setup this behaviour at once for whole test suite without tests code modification.

**Comment by feech** [comment]
Could you provide: 1. any header you want to save globally and 2. any reason to keep request body for any requests?

please, keep in mind the reason to add any entity in stubs is to resolve collisions between requests.

**Comment by cepreu2github** [comment]
Currently I working with API, where all requests goes at one URL. Kind of request determined by attributes in body. It is pretty complex API with many types of requests, but all this complexity in body. Which leaves me with not-usable rmNew and rmNone with default rules. And require to write `StubHttpClient.addBodyRule("processxml");` in ANY test.

Thre is many possibilities to encounter such API during development. For example all SOAP-based API shares same desing principle.

Also I think there is no reason, why it shouln't be configurable via annotations. Maybe you can consider to make anottation with more arguments than current @AnyStubId? Restrictions "it can be configured only via annotation" and "it can be configured only via java-code" pretty odd.

I am not interested in headers particular. Mentioned them just because there is same mechanism to specify header and body rules, so probably same general solution should be made.

In snippet above you can see I use test method name as base for stub-file name to get stub-file per test. Maybe there thould default mechanism for it? To have separate stubs for every test, but without need to repeat @AnyStubId with different `filename`. Look at this [gist](https://gist.github.com/cepreu2github/af060044b0e66e5e8e4ecc575d0bf6a6) as example of problem. I'd rather prefer to put only one annotation at test-class level with global configuration (use test method name for stub name, request mode, match by body rule). This annotation-repetition is bad.

**Comment by feech** [comment]
ah SOAP

1. to have distinct stubs for each test you only need to annotate the methods with ```@AnystubId``` without any parameters. it will build the filenames from the test method's names. 

2. to simplify "global" initialization you can create a method
```
    public static void globalHttStubSettings() {
        BaseManagerImpl.instance()
                .getBase()
                .addProperty(HTTP_PROPERTY, HTTP_PROPERTY_BODY, "processxml");
    }
```
then put the method at the beginning of each test annotated with ```@AnystubId```
or in your ```@Before``` method  (not recommended with the current version) 
or in ```@BeforeClass``` (annotation AnystubId is only on class level, no need to annotate the static method). 

3. to build reliable tests you can try RequestMode.rmTrack. but that requires deterministic behavior from your classes. It is recommended to use the mode with method level annotations.

**Comment by cepreu2github** [comment]
So there is no way to have distinct stubs for each test and "global" initialization for body rules at same time?

**Comment by feech** [comment]
- to have a distinct stub for a test: annotate it
- to set HTTP_PROPERTY_BODY for all tests in a file: call ```globalHttStubSettings()``` from ```@BeforeClass``` method

**Comment by feech** [comment]
@cepreu2github would you like to have a distinct file for each test annotated with ```@Test```?

**Comment by cepreu2github** [comment]
Yes.

**Comment by cepreu2github** [comment]
Tried it: https://gist.github.com/cepreu2github/714dffae7ae0ed7cbbb90b3934d82aae
Stub file named by test method name - it works well. But body inside file in `keys` not present. Is it should work some other way? Or there is no way to have distinct stubs for each test and "global" initialization for body rules at same time?

**Comment by feech** [comment]
At the moment there is no way to set default or global properties.

There is the PR #49 with the proposal to tackle the problem, to set default properties use an approach from the example below. 
```
       BaseManagerImpl.setDefaultInitializer(base->
               base.addProperty("aaa", "bbbb"));
```
 

To solve your problem I recommend explicitly define properties for each stub.

**Comment by feech** [comment]
release 0.4.2 includes new interface which allows to setup default properties
check ```setDefaultStubInitializer() ``` in ```BaseManagerFactory```
find [an example in tests](https://github.com/anystub/anystub/blob/master/src/test/java/org/anystub/mgmt/BaseManagerFactoryTest.java#L34)

caution: some API has changed
