### ISSUE TITLE
Support org.apache.http.entity.StringEntity inside org.anystub.http.HttpUtil#extractEntityData

### ISSUE THREAD

**Issue by cepreu4wiley** [anystub/anystub#52]
Now there no option to extract data from StringEntity so AnyStub not being able to use body as key for such requests.

**Comment by cepreu4wiley** [comment]
In case somebody encounters same problem, I found a workaround:
```
        StubHttpClient stubHttpClient = new StubHttpClient(real) {
            @Override // TODO: workaround for problem in AnyStub itself, will remove after upstream fix
            public HttpResponse execute(final HttpUriRequest httpRequest) throws IOException, ClientProtocolException {
                if (httpRequest instanceof HttpEntityEnclosingRequest) {
                    HttpEntityEnclosingRequest request = (HttpEntityEnclosingRequest)httpRequest;
                    HttpEntity entity = request.getEntity();
                    if (entity instanceof StringEntity) {
                        byte[] content = ByteStreams.toByteArray(entity.getContent());
                        String mimeType = entity.getContentType().getValue().split(";")[0].trim();
                        String charset = entity.getContentType().getValue().split(";")[1].split("=")[1].trim();
                        ContentType contentType = ContentType.create(mimeType, charset);
                        request.setEntity(new ByteArrayEntity(content, contentType));
                    }
                }
                return super.execute(httpRequest);
            }
        };
```
StubHttpClient created by code above is able to stringify StringEntity.

**Comment by feech** [comment]
in general case body is binary type. How would you extract key from binary body?

**Comment by feech** [comment]
> Now there no option to extract data from StringEntity so AnyStub not being able to use body as key for such requests.

where does StringEntity come from? 

there is a case for ByteArrayEntity which come from comes from org.springframework.web.client.RestTemplate

**Comment by cepreu4wiley** [comment]
Exactly opposite. `org.apache.http.entity.StringEntity` is for text data. I got it for `Content-Type: application/json; charset=UTF-8`. And I got `org.apache.http.entity.ByteArrayEntity#ByteArrayEntity` for `Content-Type: multipart/form-data`.

**Comment by cepreu4wiley** [comment]
at com.wiley.wpp.content.web.controller.StubTestConfig$2.execute(StubTestConfig.java:62)
	at feign.httpclient.ApacheHttpClient.execute(ApacheHttpClient.java:85)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:108)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:78)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy149.createChildrenNode(Unknown Source)
	at com.wiley.wpp.content.service.DcmContentService.createChildNode(DcmContentService.java:198)

**Comment by cepreu4wiley** [comment]
As you can see it from Feign and then ApacheHttpClient, where StubClient wrapped.

**Comment by cepreu4wiley** [comment]
From what I seeing actual place for decision is inside `feign.httpclient.ApacheHttpClient#toHttpUriRequest`.

**Comment by feech** [comment]
added support in 0.4.3

**Comment by cepreu4wiley** [comment]
Thanks for your efforts on this. Now works like a charm.
