### ISSUE TITLE
AnyStub loses body for some responses with bodyTrigger setting

### ISSUE THREAD

**Issue by cepreu4wiley** [anystub/anystub#56]
I have this happening for such request:
```
request3:
  exception: []
  keys: [POST, HTTP/1.1, 'http://ck-update-service-dev.aws.wiley.com:8080/api/v1/name/parse',
    '{"file":"AOGL976_en-US.zip"}']
  values: [HTTP/1.1, '200', '', 'Date: Tue, 26 May 2020 16:33:22 GMT', 'Content-Type:
      application/json;charset=UTF-8', 'Transfer-Encoding: chunked', 'Connection:
      keep-alive', 'Transaction-ID: f00ee744-19bd-41ef-8785-3127af44bf45', 'Transaction-ID:
      f00ee744-19bd-41ef-8785-3127af44bf45', 'Set-Cookie: WPP_AUTH_TOKEN=; Max-Age=0;
      Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=localhost; Path=/', 'Set-Cookie:
      WPP_AUTH_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTA1MTA4MDIsImV4cCI6MTU5MDUyMTYwMiwibWF4YWdlIjoiMTA4MDAiLCJpc3MiOiIzNjc3YWQwZi03YzJmLTQwZjItOGNiYS03N2E1YzUzODFlYzkiLCJzeXNpZCI6IjM2NzdhZDBmLTdjMmYtNDBmMi04Y2JhLTc3YTVjNTM4MWVjOSJ9.HjmJRATU2vmPcNyaBqQ-NhbhE-nIi2FizkkuhZ_FkGs;
      Domain=localhost; Path=/', 'X-Content-Type-Options: nosniff', 'X-XSS-Protection:
      1; mode=block', 'Cache-Control: no-cache, no-store, max-age=0, must-revalidate',
    'Pragma: no-cache', 'Expires: 0', 'X-Frame-Options: DENY', '{"locale":"en-US","report":[{"type":"INFO","created":"2020-05-26T16:33:22.426Z","message":"Request
      ''/name/parse'' with body: File(file=AOGL976_en-US.zip)"},{"type":"INFO","created":"2020-05-26T16:33:22.426Z","message":"Filename
      end with: ''.zip'' - is package."},{"type":"INFO","created":"2020-05-26T16:33:22.426Z","message":"Success
      found ''AOGL976'' code value."},{"type":"INFO","created":"2020-05-26T16:33:22.426Z","message":"Success
      found ''en-US'' locale value."},{"type":"INFO","created":"2020-05-26T16:33:22.427Z","message":"Success
      associating code ''AOGL976'' with ''Session'' package type."}],"type":"Session","code":"AOGL976"}']
```

I guess it happening because of RE for header detection inside of org.anystub.http.HttpUtil#decode.  This RE is forcing AnyStub to save body as header. Maybe it worth to always consider last key as body just having it empty for cases where no body is present?

**Comment by feech** [comment]
Thanks for your raising the issue.
Is the issue related to saving or replaying stubs?

Could you provide all settings to reproduce the issue?

**Comment by feech** [comment]
my guess is in the example you provided the part (quoted below) is the desired response body

`'{"locale":"en-US","report":[{"type":"INFO","created":"2020-05-26T16:33:22.426Z","message":"Request
      ''/name/parse'' with body: File(file=AOGL976_en-US.zip)"},{"type":"INFO","created":"2020-05-26T16:33:22.426Z","message":"Filename
      end with: ''.zip'' - is package."},{"type":"INFO","created":"2020-05-26T16:33:22.426Z","message":"Success
      found ''AOGL976'' code value."},{"type":"INFO","created":"2020-05-26T16:33:22.426Z","message":"Success
      found ''en-US'' locale value."},{"type":"INFO","created":"2020-05-26T16:33:22.427Z","message":"Success
      associating code ''AOGL976'' with ''Session'' package type."}],"type":"Session","code":"AOGL976"}'`

**Comment by feech** [comment]
if my assumption is correct find the fix in a new version
0.5.1

**Comment by cepreu4wiley** [comment]
I can confirm that 0.5.1 fixed this issue. Thanks for quick response.
